import type { TemplateManifest } from "@/core/template/manifest";
import { design } from "./designs";

/**
 * The boutique collection: refined designs in the spirit of fine printed
 * stationery — tall typography, photo cards, asymmetric names, line-drawn
 * florals, greenery, foil and letterpress. All art is original and drawn in
 * code (src/templates/shared/stationery).
 */
export const BOUTIQUE_MANIFESTS: TemplateManifest[] = [
  design({
    id: "marlowe",
    name: "Marlowe",
    tagline: "Tall capitals, a whisper of script.",
    description: "Classic white stock with towering, slender capitals, a script “and” between two fine rules and your date set in flowing calligraphy.",
    categories: ["typography", "elegant", "minimalist", "classic"],
    art: { ornament: "none", layout: "refined", letterpress: true },
    fonts: { heading: "instrument", body: "jost", accent: "pinyon" },
    palettes: ["snow", "claret", "stone", "midnight"],
    isNew: true,
  }),
  design({
    id: "horizon",
    name: "Horizon",
    tagline: "Your photo, edge to edge.",
    description: "A favourite photograph fills the whole card, with your names in airy, spaced capitals across the sky.",
    categories: ["photo", "modern", "elegant"],
    art: { ornament: "none", layout: "photo-overlay" },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["snow", "stone", "sage"],
    isNew: true,
  }),
  design({
    id: "serena",
    name: "Serena",
    tagline: "Names set apart, joined by script.",
    description: "A card with one softly rounded corner. Your names sit on either side of the page, joined by a sweeping script “and”.",
    categories: ["modern", "minimalist", "typography"],
    art: { ornament: "none", layout: "asymmetric", shape: "corner" },
    fonts: { heading: "italiana", body: "jost", accent: "pinyon" },
    palettes: ["almond", "snow", "sage", "blush"],
    isNew: true,
  }),
  design({
    id: "verdant",
    name: "Verdant",
    tagline: "Leafy branches and blush buds.",
    description: "Slender leafy branches curl in from two corners, dotted with tiny blush buds, around names in quiet spaced capitals.",
    categories: ["greenery", "floral", "elegant", "botanical"],
    art: { ornament: "vines", layout: "spaced" },
    fonts: { heading: "cormorant", body: "jost", accent: "pinyon" },
    palettes: ["blushSage", "ivory", "mist"],
    isNew: true,
  }),
  design({
    id: "wildwood",
    name: "Wildwood",
    tagline: "Wildflowers climbing the edges.",
    description: "Cornflowers, lilac and little buds climb both sides of a rounded card — light, fresh and made for garden weddings.",
    categories: ["floral", "whimsical", "outdoor", "rustic"],
    art: { ornament: "meadow-border", layout: "spaced", finish: { silhouette: "rounded" } },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["meadow", "blush", "sage"],
    isNew: true,
  }),
  design({
    id: "garden-toile",
    name: "Garden Toile",
    tagline: "Fine line florals on deep emerald.",
    description: "A landscape card bordered all round with pen-drawn peonies, blooms and leaves, and your names in calligraphy at the centre.",
    categories: ["floral", "elegant", "vintage", "luxury"],
    art: { ornament: "line-florals", layout: "script", shape: "landscape" },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["deepEmerald", "mist", "oxblood", "almond"],
    isNew: true,
  }),
  design({
    id: "gilded-garden",
    name: "Gilded Garden",
    tagline: "Gold foil flowers on slate.",
    description: "Bands of line-drawn flowers across the top and bottom, stamped in gold foil on a soft slate card.",
    categories: ["luxury", "floral", "elegant"],
    art: { ornament: "florals-band", layout: "script", finish: { foil: "gold" } },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["slate", "midnight", "navy", "emerald"],
    isNew: true,
  }),
  design({
    id: "peony-press",
    name: "Peony Press",
    tagline: "Drawn peonies, pressed into cotton.",
    description: "Delicate pen-drawn peonies gather in two corners of a letterpress card, with names in fine spaced capitals.",
    categories: ["floral", "classic", "elegant", "vintage"],
    art: { ornament: "peonies", layout: "spaced", letterpress: true, finish: { paper: "eggshell" } },
    fonts: { heading: "cormorant", body: "jost", accent: "pinyon" },
    palettes: ["pearl", "blush", "dustyBlue"],
    isNew: true,
  }),
  design({
    id: "cypress",
    name: "Cypress",
    tagline: "A photo beside flowing script.",
    description: "A landscape card: your photo on one half, your names in calligraphy on the other.",
    categories: ["photo", "romantic", "modern"],
    art: { ornament: "none", layout: "photo-side", shape: "landscape" },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["almond", "sage", "snow"],
    isNew: true,
  }),
  design({
    id: "aurelia",
    name: "Aurelia",
    tagline: "A rose gold monogram.",
    description: "Your initials in a fine circle, stamped in rose gold foil above names in elegant capitals.",
    categories: ["monogram", "luxury", "minimalist"],
    art: { ornament: "hairline", layout: "monogram", finish: { foil: "rose-gold" } },
    fonts: { heading: "cormorant", body: "jost", accent: "pinyon" },
    palettes: ["blush", "snow", "almond"],
    isNew: true,
  }),
];
