import type { StationeryArt, TemplateCategory, TemplateManifest } from "@/core/template/manifest";
import type { ThemeTokens } from "@/core/theme/tokens";
import { PALETTES, type PaletteId } from "./palettes";

/**
 * The design collection: original invitation designs drawn in code
 * (src/templates/shared/stationery). Each is a template manifest that reuses
 * an existing layout, so adding one needs no database, editor or renderer
 * change — just an entry below.
 *
 * Every design opens with its own card ("card" hero) filled in with the
 * couple's details, followed by the full invitation in the same theme.
 */

const ALL_SECTIONS = [
  "hero", "couple", "date", "countdown", "story", "ceremony", "reception",
  "venue", "gallery", "schedule", "rsvp", "closing", "footer",
] as const;

const EDITORIAL_SECTIONS = ["hero", "couple", "date", "story", "ceremony", "reception", "gallery", "schedule", "rsvp", "closing", "footer"] as const;
const EDITORIAL_ORDER = ["hero", "couple", "date", "ceremony", "reception", "schedule", "story", "gallery", "rsvp", "closing", "footer"] as const;

interface DesignSpec {
  id: string;
  name: string;
  tagline: string;
  description: string;
  categories: TemplateCategory[];
  art: StationeryArt;
  fonts: ThemeTokens["fonts"];
  /** First is the default look. */
  palettes: PaletteId[];
  radius?: number;
  shadow?: ThemeTokens["shadow"];
  renderer?: "cinematic" | "editorial";
  family?: string;
  isNew?: boolean;
}

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

export function design(spec: DesignSpec): TemplateManifest {
  const [first, ...rest] = spec.palettes;
  const editorial = spec.renderer === "editorial";
  return {
    id: spec.id,
    name: spec.name,
    tagline: spec.tagline,
    description: spec.description,
    renderer: spec.renderer ?? "cinematic",
    categories: spec.categories,
    stationery: spec.art,
    family: spec.family,
    isNew: spec.isNew,
    supportedSections: editorial ? EDITORIAL_SECTIONS : ALL_SECTIONS,
    defaultSectionOrder: editorial ? EDITORIAL_ORDER : ALL_SECTIONS,
    themeDefaults: {
      colors: { ...PALETTES[first].colors },
      fonts: spec.fonts,
      radius: spec.radius ?? 2,
      shadow: spec.shadow ?? "soft",
    },
    palettes: [
      { id: kebab(first), label: PALETTES[first].label, family: PALETTES[first].family, colors: {} },
      ...rest.map((id) => ({ id: kebab(id), label: PALETTES[id].label, family: PALETTES[id].family, colors: { ...PALETTES[id].colors } })),
    ],
    features: { opening: "none", music: true, hero: "card" },
    status: "available",
  };
}

const serif = { heading: "cormorant", body: "jost", accent: "pinyon" } as const;

export const DESIGN_MANIFESTS: TemplateManifest[] = [
  design({
    id: "delft-garland",
    name: "Delft Garland",
    tagline: "A painted wreath of leaves and blossoms.",
    description: "An oval garland of hand-drawn leaves and little blossoms circles your names, in blues inspired by painted porcelain.",
    categories: ["floral", "elegant", "traditional"],
    art: { ornament: "garland", layout: "classic" },
    fonts: serif,
    palettes: ["delft", "dustyBlue", "sage", "burgundy", "ivory"],
    family: "delft",
    isNew: true,
  }),
  design({
    id: "delft-garland-square",
    name: "Delft Garland Square",
    tagline: "The Delft garland on a square card.",
    description: "The same painted garland on a square card — compact, balanced and lovely on phones.",
    categories: ["floral", "elegant"],
    art: { ornament: "garland", layout: "classic", shape: "square" },
    fonts: serif,
    palettes: ["delft", "dustyBlue", "sage", "blush"],
    family: "delft",
    isNew: true,
  }),
  design({
    id: "four-frames",
    name: "Four Frames",
    tagline: "Four favourite photos, one simple line.",
    description: "A tidy grid of four of your photos above your names — made for couples with too many good pictures to choose one.",
    categories: ["photo", "modern", "minimalist"],
    art: { ornament: "none", layout: "photo-grid" },
    fonts: { heading: "jost", body: "jost", accent: "greatvibes" },
    palettes: ["paper", "sage", "blush", "noir"],
    radius: 0,
    renderer: "editorial",
    isNew: true,
  }),
  design({
    id: "wild-meadow",
    name: "Wild Meadow",
    tagline: "A meadow of line-drawn wildflowers.",
    description: "A border of wildflowers, grasses and seed heads grows along the bottom of the card — relaxed, natural and a little whimsical.",
    categories: ["floral", "whimsical", "greenery", "outdoor"],
    art: { ornament: "wildflowers", layout: "script" },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["ivory", "sage", "lavender", "blush", "terracotta"],
    isNew: true,
  }),
  design({
    id: "willow-arch",
    name: "Willow Arch",
    tagline: "An arched card with flowing script.",
    description: "A softly arched card with your names in a flowing script and a fine inner border that follows the curve.",
    categories: ["elegant", "romantic", "typography"],
    art: { ornament: "hairline", layout: "script", shape: "arch" },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["champagne", "blush", "sage", "dustyBlue", "midnight"],
    family: "willow",
    isNew: true,
  }),
  design({
    id: "willow",
    name: "Willow",
    tagline: "Flowing script on a classic card.",
    description: "Your names in a flowing script on a classic portrait card with a fine border.",
    categories: ["elegant", "romantic", "typography"],
    art: { ornament: "hairline", layout: "script" },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["champagne", "blush", "sage", "dustyBlue"],
    family: "willow",
  }),
  design({
    id: "harbour",
    name: "Harbour",
    tagline: "A strong double border and classic capitals.",
    description: "A bold double rule frames your names set in inscriptional capitals — formal, crisp and timeless.",
    categories: ["classic", "elegant", "traditional"],
    art: { ornament: "double-border", layout: "typographic" },
    fonts: { heading: "cinzel", body: "cormorant", accent: "pinyon" },
    palettes: ["delft", "ivory", "forest", "burgundy", "navy"],
    radius: 0,
    family: "harbour",
  }),
  design({
    id: "harbour-square",
    name: "Harbour Square",
    tagline: "The Harbour double border, square.",
    description: "Harbour's double rule and capitals on a square card.",
    categories: ["classic", "elegant"],
    art: { ornament: "double-border", layout: "typographic", shape: "square" },
    fonts: { heading: "cinzel", body: "cormorant", accent: "pinyon" },
    palettes: ["delft", "ivory", "forest", "burgundy"],
    radius: 0,
    family: "harbour",
  }),
  design({
    id: "laurel-crest",
    name: "Laurel Crest",
    tagline: "Your initials inside a laurel wreath.",
    description: "A hand-drawn laurel wreath crowns your initials, with your names in spaced capitals beneath — a crest of your own.",
    categories: ["monogram", "classic", "greenery"],
    art: { ornament: "wreath", layout: "monogram" },
    fonts: { heading: "cinzel", body: "cormorant", accent: "greatvibes" },
    palettes: ["forest", "ivory", "navy", "emerald", "burgundy"],
    family: "laurel",
    isNew: true,
  }),
  design({
    id: "laurel-crest-square",
    name: "Laurel Crest Square",
    tagline: "The laurel monogram on a square card.",
    description: "Laurel Crest's wreathed monogram on a square card.",
    categories: ["monogram", "classic"],
    art: { ornament: "wreath", layout: "monogram", shape: "square" },
    fonts: { heading: "cinzel", body: "cormorant", accent: "greatvibes" },
    palettes: ["forest", "ivory", "navy", "emerald"],
    family: "laurel",
  }),
  design({
    id: "gilded-deco",
    name: "Gilded Deco",
    tagline: "Jazz-age fans and a golden sunburst.",
    description: "Art-deco fans in every corner, a stepped sunburst and tall capitals — for glamorous evenings and grand ballrooms.",
    categories: ["luxury", "vintage", "elegant"],
    art: { ornament: "deco", layout: "typographic" },
    fonts: { heading: "marcellus", body: "jost", accent: "italiana" },
    palettes: ["midnight", "emerald", "navy", "noir", "ivory"],
    radius: 0,
    shadow: "deep",
    family: "deco",
    isNew: true,
  }),
  design({
    id: "gilded-deco-arch",
    name: "Gilded Deco Arch",
    tagline: "Art deco under an arch.",
    description: "Gilded Deco's fans and sunburst on an arched card.",
    categories: ["luxury", "vintage"],
    art: { ornament: "deco", layout: "typographic", shape: "arch" },
    fonts: { heading: "marcellus", body: "jost", accent: "italiana" },
    palettes: ["midnight", "emerald", "navy", "wine"],
    radius: 0,
    shadow: "deep",
    family: "deco",
  }),
  design({
    id: "scalloped-lace",
    name: "Scalloped Lace",
    tagline: "A scalloped edge like vintage lace.",
    description: "A scalloped border and a string of tiny pearls frame a classic layout — sweet, nostalgic and very pretty.",
    categories: ["vintage", "romantic", "whimsical"],
    art: { ornament: "scallop", layout: "classic" },
    fonts: { heading: "playfair", body: "cormorant", accent: "pinyon" },
    palettes: ["blush", "lavender", "ivory", "dustyBlue"],
  }),
  design({
    id: "olive-grove",
    name: "Olive Grove",
    tagline: "Olive branches for a sunlit wedding.",
    description: "Crossed olive branches with ripe olives, above and below — made for vineyards, courtyards and long lunches outdoors.",
    categories: ["greenery", "rustic", "outdoor"],
    art: { ornament: "olive", layout: "classic" },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["olive", "sage", "terracotta", "ivory"],
    isNew: true,
  }),
  design({
    id: "moonlit",
    name: "Moonlit",
    tagline: "A crescent moon and a sky of stars.",
    description: "A scatter of hand-drawn stars and a crescent moon — for evening vows and celebrations that go on under the night sky.",
    categories: ["whimsical", "luxury", "modern"],
    art: { ornament: "celestial", layout: "script" },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["navy", "midnight", "plum", "wine", "dustyBlue"],
    shadow: "deep",
    isNew: true,
  }),
  design({
    id: "confetti",
    name: "Confetti",
    tagline: "Bold type and a burst of confetti.",
    description: "Big, happy capitals and a shower of confetti around the edges — for couples who want the party to start with the invitation.",
    categories: ["whimsical", "modern", "typography"],
    art: { ornament: "confetti", layout: "typographic" },
    fonts: { heading: "jost", body: "jost", accent: "greatvibes" },
    palettes: ["coral", "lemon", "blush", "paper", "noir"],
    radius: 0,
    renderer: "editorial",
  }),
  design({
    id: "amalfi-tile",
    name: "Amalfi Tile",
    tagline: "Painted tiles from a coastal terrace.",
    description: "Rows of painted geometric tiles frame the card, inspired by seaside terraces and summer lunches by the water.",
    categories: ["whimsical", "outdoor", "vintage"],
    art: { ornament: "tile", layout: "classic" },
    fonts: { heading: "playfair", body: "jost", accent: "greatvibes" },
    palettes: ["delft", "lemon", "terracotta", "teal"],
    radius: 0,
    isNew: true,
  }),
  design({
    id: "morning-wash",
    name: "Morning Wash",
    tagline: "Soft watercolour blooms of colour.",
    description: "Loose washes of colour bloom at the corners like watercolour on cotton paper, with your names in a gentle script.",
    categories: ["romantic", "minimalist", "floral"],
    art: { ornament: "watercolor", layout: "script" },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["blush", "dustyBlue", "sage", "lavender", "coral"],
    shadow: "soft",
  }),
  design({
    id: "chapel-window",
    name: "Chapel Window",
    tagline: "Your photo framed in an arched window.",
    description: "Your favourite photo sits in a tall arched window, with your names beneath — simple, architectural and personal.",
    categories: ["photo", "elegant", "modern"],
    art: { ornament: "none", layout: "photo-top", shape: "arch" },
    fonts: { heading: "cormorant", body: "jost", accent: "pinyon" },
    palettes: ["ivory", "sage", "noir", "blush"],
    isNew: true,
    family: "chapel",
  }),
  design({
    id: "chapel-window-portrait",
    name: "Chapel Window Portrait",
    tagline: "A framed photo on a portrait card.",
    description: "Chapel Window's framed photo and names on a classic portrait card.",
    categories: ["photo", "elegant"],
    art: { ornament: "hairline", layout: "photo-top" },
    fonts: { heading: "cormorant", body: "jost", accent: "pinyon" },
    palettes: ["ivory", "sage", "noir", "blush"],
    family: "chapel",
  }),
  design({
    id: "satin-bow",
    name: "Satin Bow",
    tagline: "Tied with a satin bow.",
    description: "A little satin bow tops a double-framed card — a nod to ribbon-tied invitations, drawn fresh.",
    categories: ["romantic", "whimsical", "vintage"],
    art: { ornament: "ribbon", layout: "classic" },
    fonts: { heading: "cormorant", body: "cormorant", accent: "pinyon" },
    palettes: ["blush", "ivory", "dustyBlue", "burgundy", "lavender"],
    isNew: true,
  }),
  design({
    id: "limoncello",
    name: "Limoncello",
    tagline: "Lemons, leaves and summer sunshine.",
    description: "Clusters of lemons, leaves and blossoms in opposite corners — bright, sunny and perfect for summer and destination weddings.",
    categories: ["whimsical", "outdoor", "rustic"],
    art: { ornament: "citrus", layout: "script" },
    fonts: { heading: "playfair", body: "jost", accent: "greatvibes" },
    palettes: ["lemon", "ochre", "coral", "sage"],
    isNew: true,
  }),
  design({
    id: "big-day",
    name: "Big Day",
    tagline: "Your names, as big as they can be.",
    description: "A purely typographic design: your names in towering capitals and a slim ampersand — confident, modern and graphic.",
    categories: ["typography", "modern", "minimalist"],
    art: { ornament: "none", layout: "typographic" },
    fonts: { heading: "bodoni", body: "jost", accent: "bodoni" },
    palettes: ["paper", "claret", "noir", "terracotta", "delft"],
    radius: 0,
    shadow: "none",
    renderer: "editorial",
  }),
  design({
    id: "flourish",
    name: "Flourish",
    tagline: "Calligraphic swirls and a sweeping script.",
    description: "Calligraphic flourishes above and below your names, written in a sweeping script — classic romance with a light hand.",
    categories: ["typography", "elegant", "romantic"],
    art: { ornament: "flourish", layout: "script" },
    fonts: { heading: "cormorant", body: "cormorant", accent: "greatvibes" },
    palettes: ["ivory", "burgundy", "navy", "blush", "forest"],
  }),
  design({
    id: "golden-hour",
    name: "Golden Hour",
    tagline: "A full-bleed photo, names across the bottom.",
    description: "One photo fills the whole card, with your names set over it — the most personal invitation there is.",
    categories: ["photo", "modern", "romantic"],
    art: { ornament: "none", layout: "photo-full" },
    fonts: { heading: "cormorant", body: "jost", accent: "pinyon" },
    palettes: ["ivory", "noir", "sage", "blush"],
    shadow: "deep",
  }),
  design({
    id: "polaroid",
    name: "Snapshot",
    tagline: "An instant photo with a handwritten caption.",
    description: "Your photo as a tilted instant print, captioned with your names by hand — casual, fun and full of personality.",
    categories: ["photo", "whimsical", "rustic"],
    art: { ornament: "confetti", layout: "polaroid" },
    fonts: { heading: "jost", body: "jost", accent: "greatvibes" },
    palettes: ["kraft", "paper", "blush", "sage"],
    radius: 0,
    isNew: true,
  }),
  design({
    id: "kraft-twine",
    name: "Kraft & Twine",
    tagline: "Brown paper, stitched edges and a twine bow.",
    description: "Kraft-paper tones, a stitched border and a length of twine tied in a bow — honest, homespun and made for barns and gardens.",
    categories: ["rustic", "vintage", "outdoor"],
    art: { ornament: "twine", layout: "classic" },
    fonts: { heading: "playfair", body: "jost", accent: "greatvibes" },
    palettes: ["kraft", "ivory", "olive", "stone"],
    radius: 0,
  }),
  design({
    id: "quiet-line",
    name: "Quiet Line",
    tagline: "Two fine rules and nothing else.",
    description: "Two fine rules, clean capitals and a lot of white space — nothing extra, nothing missing.",
    categories: ["minimalist", "modern", "typography"],
    art: { ornament: "rule", layout: "typographic" },
    fonts: { heading: "marcellus", body: "jost", accent: "italiana" },
    palettes: ["paper", "sage", "stone", "noir"],
    radius: 0,
    shadow: "none",
    renderer: "editorial",
  }),
  design({
    id: "eucalyptus",
    name: "Eucalyptus",
    tagline: "Trailing eucalyptus in the corners.",
    description: "Round eucalyptus leaves trail in from the corners, fresh and airy, around a classic serif layout.",
    categories: ["greenery", "botanical", "modern"],
    art: { ornament: "cascade", layout: "classic" },
    fonts: { heading: "cormorant", body: "jost", accent: "pinyon" },
    palettes: ["teal", "sage", "paper", "forest"],
    isNew: true,
  }),
  design({
    id: "rose-corners",
    name: "Rose Corners",
    tagline: "Garden roses in opposite corners.",
    description: "Loosely drawn garden roses and leaves bloom in two corners — romantic, generous and unmistakably floral.",
    categories: ["floral", "romantic", "elegant"],
    art: { ornament: "rose-corners", layout: "classic" },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["blush", "burgundy", "ivory", "lavender", "roseGold"],
  }),
  design({
    id: "heritage",
    name: "Heritage",
    tagline: "An ornate frame with scrolling corners.",
    description: "A Victorian-style frame with scrolling corners and cartouches — rich, ceremonial and made for traditional celebrations.",
    categories: ["vintage", "traditional", "classic"],
    art: { ornament: "ornate", layout: "classic" },
    fonts: { heading: "cinzel", body: "cormorant", accent: "pinyon" },
    palettes: ["burgundy", "forest", "navy", "ivory", "wine"],
    radius: 0,
  }),
  design({
    id: "sunset-arch",
    name: "Sunset Arch",
    tagline: "A clean arch in warm, earthy tones.",
    description: "A modern arched card with bold capitals in warm, earthy colours — simple, sculptural and very now.",
    categories: ["modern", "minimalist", "typography"],
    art: { ornament: "none", layout: "typographic", shape: "arch" },
    fonts: { heading: "jost", body: "jost", accent: "italiana" },
    palettes: ["terracotta", "sage", "stone", "noir", "ochre"],
    radius: 0,
    renderer: "editorial",
  }),
  design({
    id: "falling-petals",
    name: "Falling Petals",
    tagline: "Petals drifting across the card.",
    description: "A drift of petals falls around your names in a light, airy layout — gentle, romantic and a little playful.",
    categories: ["romantic", "whimsical", "floral"],
    art: { ornament: "petals", layout: "script" },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["blush", "roseGold", "lavender", "coral"],
  }),
  design({
    id: "circle-monogram",
    name: "Circle Monogram",
    tagline: "A fine ring around your initials.",
    description: "Your initials inside a single fine ring, with spaced capitals below — understated, modern and elegant.",
    categories: ["monogram", "minimalist", "modern"],
    art: { ornament: "none", layout: "monogram", shape: "square" },
    fonts: { heading: "bodoni", body: "jost", accent: "italiana" },
    palettes: ["paper", "navy", "forest", "blush", "noir"],
    radius: 0,
    renderer: "editorial",
  }),
  design({
    id: "garden-stems",
    name: "Garden Stems",
    tagline: "Tall flowering stems at either side.",
    description: "Two tall flowering stems rise up either side of the card, framing your names like a garden path.",
    categories: ["floral", "greenery", "botanical"],
    art: { ornament: "stems", layout: "classic" },
    fonts: { heading: "cormorant", body: "jost", accent: "pinyon" },
    palettes: ["sage", "ivory", "blush", "dustyBlue"],
  }),
];
