import type { TemplateManifest } from "@/core/template/manifest";
import { design } from "./designs";

/**
 * The keepsake collection: original cards in the spirit of popular
 * invitation styles — velvet tulips in a lace oval, a wedding car, a pressed
 * flower collage, line-drawn gardens, gilded leaves, calla lilies, a crest,
 * split arches, a rose arch, gardenias and three photo cards. Everything is
 * drawn in code (src/templates/shared/stationery); no third-party artwork.
 * Designs marked with a blessing open with بسم الله الرحمن الرحيم (it can be
 * switched on or off for any card).
 */
export const KEEPSAKE_MANIFESTS: TemplateManifest[] = [
  design({
    id: "velvet-tulips",
    name: "Velvet Tulips",
    tagline: "Cream tulips and a lace oval on velvet.",
    description: "Feathered cream tulips reach in from two corners of a deep velvet card, around an oval of lace and names in gold calligraphy — opening with the Bismillah.",
    categories: ["floral", "luxury", "traditional", "elegant"],
    art: { ornament: "tulips-lace", layout: "formal-script", finish: { blessing: "bismillah" } },
    fonts: { heading: "cormorant", body: "jost", accent: "pinyon" },
    palettes: ["tulipWine", "tulipNight", "emerald"],
    isNew: true,
  }),
  design({
    id: "joyride",
    name: "Joyride",
    tagline: "The wedding car, flowers and all.",
    description: "A hand-drawn vintage car dressed in flowers and ribbons, two rings, a pair of birds and your date on the number plate.",
    categories: ["whimsical", "vintage", "modern"],
    art: { ornament: "curls", layout: "drive", sample: { eyebrow: "we're getting married!" } },
    fonts: { heading: "jost", body: "jost", accent: "caveat" },
    palettes: ["carRed", "carNavy", "carGreen"],
    isNew: true,
  }),
  design({
    id: "pressed-keepsake",
    name: "Pressed Keepsake",
    tagline: "A torn-paper collage with a pressed flower.",
    description: "Your photo torn across warm paper, a painted label, a pressed flower held down with tape and your names in flowing script.",
    categories: ["photo", "rustic", "vintage", "romantic"],
    art: { ornament: "none", layout: "torn-photo", finish: { paper: "natural" }, sample: { eyebrow: "The wedding of" } },
    fonts: { heading: "cormorant", body: "jost", accent: "greatvibes" },
    palettes: ["collage", "collageRose"],
  }),
  design({
    id: "botanical-line",
    name: "Botanical Line",
    tagline: "Pen-drawn gardens and a date row.",
    description: "Layered line-drawn flowers fill two corners; your names in script, the day set out across a row of fine rules.",
    categories: ["greenery", "botanical", "floral", "modern"],
    art: { ornament: "line-garden", layout: "date-row" },
    fonts: { heading: "jost", body: "jost", accent: "greatvibes" },
    palettes: ["lineGreen", "lineBlue", "sage"],
  }),
  design({
    id: "wild-garden",
    name: "Wild Garden",
    tagline: "Line-drawn gardens, names in script.",
    description: "The same pen-drawn garden with your names stacked in script and an italic invitation line.",
    categories: ["greenery", "floral", "elegant"],
    art: { ornament: "line-garden", layout: "script-date" },
    fonts: { heading: "cormorant", body: "cormorant", accent: "allura" },
    palettes: ["lineBlue", "lineGreen", "blush"],
  }),
  design({
    id: "golden-fronds",
    name: "Golden Fronds",
    tagline: "Gilded leaves and airy calligraphy.",
    description: "Long gilded leaves drift in from every corner around names in airy calligraphy and a softly ruled date.",
    categories: ["elegant", "minimalist", "greenery", "luxury"],
    art: { ornament: "gold-leaves", layout: "script-date" },
    fonts: { heading: "cormorant", body: "cormorant", accent: "allura" },
    palettes: ["goldLeaf", "goldBlush", "sage"],
  }),
  design({
    id: "calla-lily",
    name: "Calla Lily",
    tagline: "Copper calla lilies on textured paper.",
    description: "Fine copper drawings of calla lilies and tropical leaves frame formal calligraphy on softly textured paper.",
    categories: ["elegant", "botanical", "classic", "vintage"],
    art: { ornament: "calla", layout: "formal-script", finish: { paper: "eggshell" } },
    fonts: { heading: "cormorant", body: "cormorant", accent: "pinyon" },
    palettes: ["calla", "snow", "blush"],
  }),
  design({
    id: "velvet-calla",
    name: "Velvet Calla",
    tagline: "Calla lilies drawn on midnight.",
    description: "The calla lily drawing in warm copper on a midnight card, with gold calligraphy.",
    categories: ["luxury", "botanical", "elegant"],
    art: { ornament: "calla", layout: "formal-script" },
    fonts: { heading: "cormorant", body: "cormorant", accent: "pinyon" },
    palettes: ["tulipNight", "tulipWine", "emerald"],
  }),
  design({
    id: "baroque-crest",
    name: "Baroque Crest",
    tagline: "Your initials in an ornate rose gold crest.",
    description: "An ornate cartouche of scrolls and leaves, stamped in rose gold foil around your initials, on textured paper framed by calla lilies.",
    categories: ["monogram", "luxury", "classic"],
    art: { ornament: "calla", layout: "crest", finish: { foil: "rose-gold", paper: "eggshell" }, sample: { eyebrow: "Please join us for the wedding of" } },
    fonts: { heading: "cormorant", body: "cormorant", accent: "pinyon" },
    palettes: ["calla", "ivory", "snow"],
  }),
  design({
    id: "gilded-crest",
    name: "Gilded Crest",
    tagline: "A gold crest among gilded leaves.",
    description: "The ornate crest stamped in gold foil, framed by long gilded leaves.",
    categories: ["monogram", "luxury", "elegant"],
    art: { ornament: "gold-leaves", layout: "crest", finish: { foil: "gold" }, sample: { eyebrow: "Please join us for the wedding of" } },
    fonts: { heading: "cormorant", body: "cormorant", accent: "pinyon" },
    palettes: ["goldLeaf", "snow", "goldBlush"],
  }),
  design({
    id: "twilight-arch",
    name: "Twilight Arch",
    tagline: "Two arches at dusk, painted roses.",
    description: "Two overlapping arched panels — your names on one, the date and place on the other — under painted roses and an arc of “Save the date”.",
    categories: ["floral", "modern", "romantic"],
    art: { ornament: "none", layout: "split-arch", sample: { eyebrow: "Save the date", line: "joyfully invite you to celebrate their wedding" } },
    fonts: { heading: "jost", body: "jost", accent: "pinyon" },
    palettes: ["twilight", "twilightGreen"],
    isNew: true,
  }),
  design({
    id: "rose-arch",
    name: "Rose Arch",
    tagline: "An arched panel framed in roses.",
    description: "A white arched panel set into a border of painted roses and leaves, with the Bismillah, names in calligraphy and the date between fine bars.",
    categories: ["floral", "traditional", "romantic", "elegant"],
    art: { ornament: "rose-border", layout: "arch-panel", finish: { blessing: "bismillah" }, sample: { eyebrow: "Please join us to celebrate the wedding of" } },
    fonts: { heading: "cormorant", body: "jost", accent: "pinyon" },
    palettes: ["roseArch", "blush", "dustyBlue"],
    isNew: true,
  }),
  design({
    id: "gardenia",
    name: "Gardenia",
    tagline: "White gardenias and soft green leaves.",
    description: "White gardenias and watercolour leaves in the corners, the Bismillah above names in calligraphy, and the date set between two bars.",
    categories: ["greenery", "floral", "traditional", "elegant"],
    art: { ornament: "gardenia", layout: "script-bars", finish: { blessing: "bismillah" }, sample: { eyebrow: "You are invited to the wedding of" } },
    fonts: { heading: "jost", body: "jost", accent: "pinyon" },
    palettes: ["gardenia", "ivory", "blushSage"],
    isNew: true,
  }),
  design({
    id: "bon-voyage",
    name: "Bon Voyage",
    tagline: "A boarding pass for the two of you.",
    description:
      "A landscape boarding pass: your names as the passengers, the date, time and venue as the flight details, a dotted route from today to forever and a tear-off stub with your initials. The back is a gold-stamped passport, the details card is a travel note with an arrival stamp, and the envelope is sealed with a plane.",
    categories: ["modern", "luxury", "typography"],
    art: { ornament: "none", layout: "boarding-pass", shape: "landscape", sample: { eyebrow: "Together with their families", line: "invite you to fly away to their wedding" } },
    fonts: { heading: "didone", body: "spacemono", accent: "allura" },
    palettes: ["voyageMidnight", "voyageNavy", "voyageForest"],
    isNew: true,
  }),
  design({
    id: "golden-oval",
    name: "Golden Oval",
    tagline: "Your photo in a gold oval.",
    description: "A landscape card: your photo in a gilded oval among leaves and a wash of gold, your names in tall spaced capitals beside it.",
    categories: ["photo", "luxury", "greenery"],
    art: { ornament: "none", layout: "oval-photo", shape: "landscape", sample: { eyebrow: "With their families, you are invited to the wedding of" } },
    fonts: { heading: "cormorant", body: "cormorant", accent: "pinyon" },
    palettes: ["goldenOval", "sage", "snow"],
    isNew: true,
  }),
  design({
    id: "save-the-date",
    name: "Save the Date",
    tagline: "A full photo with the date up front.",
    description: "A square card: your photo softly darkened, the day, month and year in large numerals, names in script and two framed details.",
    categories: ["photo", "modern", "rustic"],
    art: { ornament: "none", layout: "photo-details", shape: "square", sample: { eyebrow: "Save the date", line: "The wedding of" } },
    fonts: { heading: "jost", body: "jost", accent: "greatvibes" },
    palettes: ["keepsake", "stone"],
  }),
  design({
    id: "monochrome-bloom",
    name: "Monochrome Bloom",
    tagline: "Half photo, half fine line flowers.",
    description: "A landscape card: your photo on one half; on the other, names in script, the date between two bars and fine black line flowers.",
    categories: ["photo", "minimalist", "modern"],
    art: { ornament: "bloom-corners", layout: "photo-half", shape: "landscape", sample: { eyebrow: "The wedding of" } },
    fonts: { heading: "jost", body: "jost", accent: "greatvibes" },
    palettes: ["monoBloom", "sage", "blush"],
  }),
];
